spring:
  datasource:
    url: jdbc:mysql://localhost:3306/g_43_praxis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5

#server:
#  port: 8100

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

key:
  access: wNhl08SeojphfFnpUI8I5jsqFpUSFrCB9nFOdAWUpLw=
  refresh: SxlKdkim9UR0Bd6CGJLFDI6R4HcnnDmaxV1AvBZhZ6A=

messages:
  hello: Hello from local application!